### PR TITLE
add support for SDL_image

### PR DESCRIPTION
**Pull request by g-w1**

### CODE REVIEW

**Comment by MasterQ32** [comment]
The test suite now needs to link `SDL2_image`. Apart from that: :+1:

**Comment by MasterQ32** [comment]
@g-w1: do you want to add the link command to the test suite?

**Comment by g-w1** [comment]
Whoops, not at computer right now. Is it possible for you to do it?
If not, I can probably do it in a day or two.

**Comment by g-w1** [comment]
done.

**Pull request merged**
