### PR TITLE
Fix switched src and dst rectangle

### PR DESCRIPTION
**Pull request by jgollenz**

### CODE REVIEW

**Comment by MasterQ32** [comment]
Why do this change? This will break all projects that use this code right now without telling them. I swapped the parameters here by choice in the original implementation.

**Comment by jgollenz** [comment]
I came to think of that as well after I created the PR. My gut reaction just was that this must be some sort of mistake that went unnoticed. Probably should have made an issue first. But I'm probably not the only person to find this confusing / use it incorrectly by accident: https://github.com/zigimg/sdl-example/blob/master/src/main.zig#L48

What was the reasoning behind switching the parameters?

**Comment by MasterQ32** [comment]
> What was the reasoning behind switching the parameters?

`src_rect` is not used very often, so i pack optional parameters to the end so you can just pad all of them with default values and don't care. But SDL sometimes mixes optional and non-"optional" parameters. Sure, `dst_rect` is also optional, but the use case of painting the full screen is not very often required

**Comment by jgollenz** [comment]
Wouldn't I use `src_rect` the second I have a sprite sheet? And SDL being a 2D library I would assume it gets used a lot with sprite sheets. But I'm not an experienced user of SDL, maybe there is a better way to do that.

**Comment by jgollenz** [comment]
As this is not an error but expected behavior, I will close this PR.

**Pull request closed without merging**
